### ISSUE TITLE
Ticking entity crash when assembling rocket

### ISSUE THREAD

**Issue by Aabyonis** [RealAntEngineer/creating_space#107]
[crash-2025-06-27_15.16.46-server.txt](https://github.com/user-attachments/files/20945451/crash-2025-06-27_15.16.46-server.txt)

**Comment by RealAntEngineer** [comment]
this is not sufficient, please give out the log

**Comment by SDSCodes22** [comment]
I am also encountering this on NeoForge 1.21.1
It occurs when pressing "Assemble" on the rocket control. 
Binary testing to identify the mod responsible has been undertaken and it is without a doubt, an issue of Creating Space.
```
Description: Ticking block entity
java.lang.IllegalStateException: Registry not present for DeferredHolder{ResourceKey[creatingspace:propellant_type / creatingspace:methalox]}: creatingspace:propellant_type
```

This seems to be the main log error, however a full crash log may be seen here: https://mclo.gs/ARXzbTk

I really hope that this can be fixed promptly because I really would like to play this mod!

**Comment by RealAntEngineer** [comment]
@SDSCodes22 your crash is very different, it's due to minecraft not detecting the propellant registry, I see that you have a bunch of optimisation mods, can you retry without them ?

**Comment by RealAntEngineer** [comment]
the initial crash reported in this issue was fixed in the 1.7.15 version

**Comment by RealAntEngineer** [comment]
tried on my computer with the following mod list and it worked fine

		Architectury 13.0.8 (architectury)
		Bookshelf 21.1.81 (bookshelf)
		Carry On 2.2.4 (carryon)
		Cloth Config v15 API 15.0.140 (cloth_config)
		conditional mixin 0.6.4 (conditional_mixin)
		Controlling 19.0.5 (controlling)
		Create 6.0.10 (create)
		Create Hypertube 0.4.0-COMPAT (create_hypertube)
		Create Mechanical Extruder 1.21.1-2.2.0-6.0.8 (create_mechanical_extruder)
		Create Sifter 1.21.1-2.2.0 (createsifter)
		Create Slice & Dice 4.2.4 (sliceanddice)
		Create: Copycats+ 3.0.4+mc.1.21.1-neoforge (copycats)
		Create: Currency Shops 1.21.1-0.1.1 (create_currency_shops)
		Create: Dragons Plus 1.10.0b (create_dragons_plus)
		Create: Enchantment Industry 2.3.1 (create_enchantment_industry)
		Create: Numismatics 1.0.19integration+neoforge-mc1.21.1-local (numismatics)
		Create: Power Grid 0.5.5.1 (powergrid)
		Create: Steam 'n' Rails 1.21.1 0.1.0+neoforge-mc1.21.1 (railways)
		Create: Threaded Trains 1.0.0 (createthreadedtrains)
		create_enchantment_industry_plus 1.1.1 (create_enchantment_industry_plus)
		Creating Rotation Operated With Nuclear Science 2.1.5 (crowns)
		Creating Space 1.7.16 (creatingspace)
		Curios API 9.5.1+1.21.1 (curios)
		Farmer's Delight 1.3.0 (farmersdelight)
		Ferrite Core 7.0.3 (ferritecore)
		Flywheel 1.0.6 (flywheel)
		Formic API 2.2.5 (formicapi)
		FTB Chunks 2101.1.14 (ftbchunks)
		FTB Library 2101.1.31 (ftblibrary)
		FTB Quests 2101.1.24 (ftbquests)
		FTB Teams 2101.1.10 (ftbteams)
		FTB XMod Compat 21.1.8 (ftbxmodcompat)
		Immersive Aircraft 1.4.3+1.21.1 (immersive_aircraft)
		Just Enough Items 19.27.0.336 (jei)
		KubeJSCurios 1.0.4 (kubejs_curios)
		Lithium 0.15.3+mc1.21.1 (lithium)
		Loading Profiler 1.0.1 (loadingprofiler)
		Loading Profiler Bootstrap 1.0.0 (loadingprofilerbootstrap)
		Mechanicals Lib 1.1.0 (mechanicals)
		Minecraft 1.21.1 (minecraft)
		ModernFix 5.27.4+mc1.21.1 (modernfix)
		More Create Burners 1.21.1-0.3.6 (moreburners)
		Mouse Tweaks 2.26.1 (mousetweaks)
		Nature's Compass 1.21.1-3.4.0-neoforge (naturescompass)
		NeoForge 21.1.226 (neoforge)
		Ok Zoomer 10.0.0-beta.13 (ok_zoomer)
		OpenLoader 21.1.5 (openloader)
		Ponder 1.0.82+mc1.21.1 (ponder)
		PonderJS 1.21.1-2.4.0 (ponderjs)
		PrickleMC 21.1.11 (prickle)
		Rhino 2101.2.7-build.81 (rhino)
		Sable Companion 1.5.0 (sablecompanion)
		Searchables 1.0.2 (searchables)
		Simple Voice Chat 1.21.1-2.6.16 (voicechat)
		Sophisticated Backpacks 3.25.41 (sophisticatedbackpacks)
		Sophisticated Core 1.4.29 (sophisticatedcore)
		spark 1.10.124 (spark)
		Terralith 2.5.8 (terralith)
		Wrench Wrapper 0.8.1 (wrench_wrapper)
		Wrench Wrapper (Backend) 0.8.1 (wrench_wrapper_backend)

**Comment by SDSCodes22** [comment]
Hi @RealAntEngineer ! Sorry for re-opening this even though my issue you say is unrelated - based on the title I assumed they were.

My issue persists (with the same cause and main crash exception) with a minimal mod setup consisting of just Create, Creating Space, Create Aeronautics, Create Interiors, Create Crafts and Additions and Sable.
Are there any known incompatibilities with these mods? I cannot load my world without them right now and I really wanted to combine Creating Space with my existing mods.
 
This is my new crash log: https://mclo.gs/SXbI4Vy

Sorry for the troubles but I hope this can be resolved!

**Comment by RealAntEngineer** [comment]
I have found the issue, it's caused by the 2 legacy engine (the one that are not craftable in the creative menu) I will fix it in the next patch, don't use them until then
